services:
  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    env_file:
      - .env
    volumes:
      - ./services/app:/app

volumes:
  postgres_data:

